version: "3.8"
 
services:
 mysqldb:
   container_name: mysqldb
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: product_db
   networks:
     springboot-mysql-net:

 springboot-resful-webservices:
    container_name: springboot-resful-webservices 
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9092:9091" 
    depends_on:
      - mysqldb
    networks:
     springboot-mysql-net:
    restart: on-failure
networks:
 springboot-mysql-net: